# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 4.1.2 on 2022-12-07 16:59

from django.db import connection
from django.db import migrations


def generate_issue_links(apps, schema_editor):
    """Generate the IssueLink M2M table from issues' FK to the diff of a revision"""
    with connection.cursor() as cursor:
        print("Copying all issue links to diffs on the M2M table…")
        cursor.execute(
            """
            INSERT INTO issues_issuelink
              (id, issue_id, diff_id, revision_id)
            SELECT
              (ROW_NUMBER() OVER(ORDER BY issue.created)),
              issue.id,
              issue.old_diff_id,
              diff.revision_id
            FROM (
              issues_issue AS issue
              INNER JOIN issues_diff AS diff
              ON (issue.old_diff_id = diff.id)
            );
            """
        )
        cursor.fetchone()


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_issuelink_initial"),
    ]

    operations = [
        # Fill the M2M table
        migrations.RunPython(
            generate_issue_links,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        # Drop old FK
        migrations.RemoveField(
            model_name="issue",
            name="old_diff",
        ),
    ]
