# Generated by Django 5.1.15 on 2026-03-06 10:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0017_rename_phid_diff_provider_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diff",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
